name: Download Projects

on:
    schedule:
        -   cron: 34 0 * * *
    workflow_dispatch:

permissions: write-all

jobs:
    laravel:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "11.x", "12.x", "master" ]
        with:
            project: Laravel Framework ${{ matrix.version }}
            paths: source/framework/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/framework/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=framework \
                    --ver=${{ matrix.version }} \
                    --copy=src/Illuminate/Translation/lang

    breeze:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "2.x", "master" ]
        with:
            project: Laravel Breeze ${{ matrix.version }}
            paths: source/breeze/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/breeze/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=breeze \
                    --ver=${{ matrix.version }}

    cashier_stripe:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "15.x", "master" ]
        with:
            project: Laravel Cashier Stripe ${{ matrix.version }}
            paths: source/cashier/stripe/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/cashier-stripe/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=cashier/stripe \
                    --ver=${{ matrix.version }}

    fortify:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "1.x", "master" ]
        with:
            project: Laravel Fortify ${{ matrix.version }}
            paths: source/fortify/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/fortify/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=fortify \
                    --ver=${{ matrix.version }}

    jetstream:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "5.x", "master" ]
        with:
            project: Laravel Jetstream ${{ matrix.version }}
            paths: source/jetstream/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/jetstream/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=jetstream \
                    --ver=${{ matrix.version }}

    nova:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                nova:
                    - { branch: "4.x", version: "4.0" }
                    - { branch: "5.x", version: "5.0" }
        secrets:
            novaRepository: ${{ secrets.LARAVEL_REPOSITORY }}
        with:
            project: Laravel Nova ${{ matrix.nova.branch }}
            paths: source/jetstream/${{ matrix.nova.branch }}/*
            novaRepository: ${{ secrets.novaRepository }}
            commands: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"

                composer config repositories.nova composer ${{ secrets.novaRepository }}
                composer require laravel/nova:^${{ matrix.nova.version }}
                
                cp vendor/laravel/nova/resources/lang/en.json source/nova/${{ matrix.nova.branch }}/nova.json -f
                cp vendor/laravel/nova/resources/lang/en/validation.php source/nova/${{ matrix.nova.branch }}/validation.php -f

                composer remove laravel/nova
                git checkout HEAD -- composer.json

    nova_log_viewer:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "main" ]
        with:
            project: Laravel Nova Log Viewer ${{ matrix.version }}
            paths: source/nova/log-viewer/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/nova-log-viewer/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=nova/log-viewer \
                    --ver=${{ matrix.version }}

    nova_dusk_suite:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "master" ]
        with:
            project: Laravel Nova Dusk Suite ${{ matrix.version }}
            paths: source/nova/dusk-suite/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/nova-dusk-suite/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=nova/dusk-suite \
                    --ver=${{ matrix.version }} \
                    --copy=lang

    ui:
        uses: Laravel-Lang/.github/.github/workflows/download.yml@main
        strategy:
            fail-fast: true
            matrix:
                version: [ "4.x", "master" ]
        with:
            project: Laravel UI ${{ matrix.version }}
            paths: source/ui/${{ matrix.version }}/*
            commands: |
                vendor/bin/lang download \
                    --url=https://github.com/laravel/ui/archive/refs/heads/${{ matrix.version }}.zip \
                    --project=ui \
                    --ver=${{ matrix.version }}
