name: Release Drafter

on:
  push:
    branches:
      - main
  release:
    types:
      - unpublished
  workflow_dispatch:

permissions: write-all

jobs:
    Update:
        uses: Laravel-Lang/.github/.github/workflows/release-drafter.yml@main
