name: Title

on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled

jobs:
  Check:
    uses: Laravel-Lang/.github/.github/workflows/title-checker.yml@main
