name: Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

permissions:
  pull-requests: write

jobs:
  Check:
    uses: Laravel-Lang/.github/.github/workflows/title-checker.yml@main
