name: Title

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

permissions: write-all

jobs:
  Check:
    uses: Laravel-Lang/.github/.github/workflows/title-checker.yml@main
